import type { DigestItem, Job, HiringStatus, LocationType, Signal, Trend } from "@/types";

export const jobs: Job[] = [
  {
    id: "job_001",
    role: "Frontend Dev",
    title: "Frontend Developer (React)",
    company: "Northbridge Systems",
    location: "Remote, US",
    locationType: "Remote",
    companySize: "201-1000",
    salary: "$140k-$190k",
    fundingStage: "Series B",
    deadline: "25 DEC",
    skills: ["React", "TypeScript", "Next.js", "Tailwind"],
    postedDays: 3,
    hiringStatus: "HIRING_ACTIVE" satisfies HiringStatus,
    saved: true,
    applied: true,
    experienceTier: "II",
    emailAvailable: true,
    applyAvailable: true,
  },
  {
    id: "job_002",
    role: "Backend Dev",
    title: "Backend Engineer (Node + Postgres)",
    company: "Blackbox Ledger",
    location: "Austin, TX",
    locationType: "On-site",
    companySize: "51-200",
    salary: "$130k-$175k",
    fundingStage: "Series A",
    skills: ["Node.js", "PostgreSQL", "REST", "Testing"],
    postedDays: 7,
    hiringStatus: "HIRING_ACTIVE",
    saved: false,
    applied: false,
    experienceTier: "I",
    emailAvailable: false,
    applyAvailable: true,
  },
  {
    id: "job_003",
    role: "Full Stack",
    title: "Full Stack Engineer (Next + API)",
    company: "Cinder Commerce",
    location: "Berlin, DE",
    locationType: "Hybrid",
    companySize: "201-1000",
    salary: "$150k-$210k",
    fundingStage: "Series C",
    deadline: "10 JAN",
    skills: ["React", "Next.js", "TypeScript", "SQL", "OAuth"],
    postedDays: 5,
    hiringStatus: "HIRING_ACTIVE",
    saved: false,
    applied: true,
    experienceTier: "III",
    emailAvailable: true,
    applyAvailable: true,
  },
  {
    id: "job_004",
    role: "Data Engineer",
    title: "Data Engineer (Pipelines + Warehousing)",
    company: "Aurum Insights",
    location: "Remote, EU",
    locationType: "Remote",
    companySize: "51-200",
    salary: "$120k-$170k",
    fundingStage: "Bootstrapped",
    skills: ["Python", "SQL", "Airflow", "dbt"],
    postedDays: 2,
    hiringStatus: "HIRING_ACTIVE",
    saved: true,
    applied: false,
    experienceTier: "II",
    emailAvailable: false,
    applyAvailable: true,
  },
  {
    id: "job_005",
    role: "ML Engineer",
    title: "ML Engineer (LLM Serving)",
    company: "Atlas Interview AI",
    location: "Toronto, CA",
    locationType: "Hybrid",
    companySize: "201-1000",
    salary: "$165k-$230k",
    fundingStage: "Series D",
    deadline: "18 DEC",
    skills: ["Python", "PyTorch", "LLMs", "FastAPI"],
    postedDays: 9,
    hiringStatus: "SLOW_HIRING",
    saved: false,
    applied: false,
    experienceTier: "III",
    emailAvailable: false,
    applyAvailable: false,
  },
  {
    id: "job_006",
    role: "DevOps/SRE",
    title: "DevOps Engineer (K8s + Terraform)",
    company: "Ironleaf Infra",
    location: "Seattle, WA",
    locationType: "On-site",
    companySize: "1000+",
    salary: "$175k-$240k",
    fundingStage: "Series E",
    deadline: "05 NOV",
    skills: ["Kubernetes", "Terraform", "AWS", "Observability"],
    postedDays: 12,
    hiringStatus: "HIRING_ACTIVE",
    saved: false,
    applied: true,
    experienceTier: "IV",
    emailAvailable: true,
    applyAvailable: true,
  },
  {
    id: "job_007",
    role: "Product Manager",
    title: "Technical Product Manager (Platform)",
    company: "SignalForge",
    location: "Remote, UK",
    locationType: "Remote",
    companySize: "51-200",
    salary: "$140k-$200k",
    fundingStage: "Series B",
    skills: ["Roadmapping", "Metrics", "APIs", "Stakeholders"],
    postedDays: 6,
    hiringStatus: "SLOW_HIRING",
    saved: false,
    applied: false,
    experienceTier: "II",
    emailAvailable: false,
    applyAvailable: false,
  },
  {
    id: "job_008",
    role: "Mobile Dev",
    title: "Mobile Engineer (React Native)",
    company: "Harbor Atlas",
    location: "Chicago, IL",
    locationType: "Hybrid",
    companySize: "201-1000",
    salary: "$135k-$185k",
    fundingStage: "Series A",
    deadline: "30 DEC",
    skills: ["React Native", "TypeScript", "CI/CD", "Performance"],
    postedDays: 4,
    hiringStatus: "HIRING_ACTIVE",
    saved: true,
    applied: false,
    experienceTier: "II",
    emailAvailable: true,
    applyAvailable: true,
  },
  {
    id: "job_009",
    role: "QA Engineer",
    title: "QA Engineer (Automation + Cypress)",
    company: "Kestrel Testing Co.",
    location: "Remote, US",
    locationType: "Remote",
    companySize: "11-50",
    salary: "$105k-$150k",
    fundingStage: "Series Seed",
    skills: ["Cypress", "TypeScript", "Playwright", "CI"],
    postedDays: 10,
    hiringStatus: "SLOW_HIRING",
    saved: false,
    applied: false,
    experienceTier: "I",
    emailAvailable: false,
    applyAvailable: true,
  },
  {
    id: "job_010",
    role: "Security",
    title: "Application Security Engineer",
    company: "Dreadnought Security",
    location: "On-site, NYC",
    locationType: "On-site",
    companySize: "1000+",
    salary: "$190k-$260k",
    fundingStage: "Series C",
    deadline: "02 FEB",
    skills: ["AppSec", "Threat Modeling", "SAST", "Secure SDLC"],
    postedDays: 1,
    hiringStatus: "HIRING_ACTIVE",
    saved: false,
    applied: false,
    experienceTier: "IV",
    emailAvailable: true,
    applyAvailable: false,
  },
];

export const trends: Trend[] = [
  { skill: "React", percentage: 87, weeklyChange: +6 },
  { skill: "TypeScript", percentage: 82, weeklyChange: +4 },
  { skill: "Python", percentage: 76, weeklyChange: +3 },
  { skill: "AWS", percentage: 70, weeklyChange: +2 },
  { skill: "SQL", percentage: 65, weeklyChange: +5 },
  { skill: "Kubernetes", percentage: 61, weeklyChange: +1 },
  { skill: "Terraform", percentage: 58, weeklyChange: +2 },
  { skill: "LLMs", percentage: 54, weeklyChange: +7 },
];

export const signals: Signal[] = [
  {
    date: "2026-03-18",
    headline: "Hiring velocity spikes for React + TypeScript stacks",
    category: "HIRING",
    source: "Weekly job velocity scan",
  },
  {
    date: "2026-03-15",
    headline: "Layoff signal weakens for data engineering roles",
    category: "LAYOFF",
    source: "Forum + board aggregation",
  },
  {
    date: "2026-03-12",
    headline: "Funding rounds increase for infra tooling teams",
    category: "FUNDING",
    source: "Funding digest model",
  },
  {
    date: "2026-03-08",
    headline: "Security hiring remains steady; AppSec SDLC emphasized",
    category: "SKILLS",
    source: "Role taxonomy matcher",
  },
  {
    date: "2026-03-04",
    headline: "LLM serving roles shift toward FastAPI + evaluation",
    category: "SKILLS",
    source: "Resume-to-role alignment signal",
  },
];

export const digestItems: DigestItem[] = [
  {
    id: "dig_001",
    headline: "Top skill this week: React demand remains brutally consistent",
    source: "TazaKhabar signal engine",
    summary: "Hiring posts show steady React + TS clusters across remote and hybrid teams.",
    category: "SKILLS",
    readTime: "4 min",
    featured: true,
  },
  {
    id: "dig_002",
    headline: "Backend roles prefer Postgres + testing discipline",
    source: "Job board harmonizer",
    summary: "Candidates who can show reliable integration tests get filtered up the pipeline.",
    category: "HIRING",
    readTime: "3 min",
  },
  {
    id: "dig_003",
    headline: "Layoff signal cools for data engineering, heats for platform",
    source: "Composite risk model",
    summary: "Warehouse + pipeline roles stabilize while platform SRE hiring grows.",
    category: "LAYOFFS",
    readTime: "5 min",
  },
  {
    id: "dig_004",
    headline: "Funding: infra tooling teams are the cleanest bet",
    source: "Funding classifier",
    summary: "Recent rounds disproportionately target Kubernetes and observability stacks.",
    category: "FUNDING",
    readTime: "4 min",
  },
  {
    id: "dig_005",
    headline: "LLM serving shifts from training to evaluation workflows",
    source: "Model-to-market map",
    summary: "Expect more emphasis on metrics, offline evaluation, and prompt regression suites.",
    category: "SKILLS",
    readTime: "6 min",
  },
  {
    id: "dig_006",
    headline: "AppSec demand: threat modeling becomes explicit",
    source: "Role taxonomy matcher",
    summary: "Job descriptions increasingly call out threat models and secure SDLC artifacts.",
    category: "SKILLS",
    readTime: "3 min",
  },
  {
    id: "dig_007",
    headline: "Hiring velocity: frontend remains dominant; mobile follows",
    source: "Velocity probe",
    summary: "Frontends lead; mobile teams ramp with performance and CI/CD expectations.",
    category: "HIRING",
    readTime: "4 min",
  },
  {
    id: "dig_008",
    headline: "Salary ranges widen slightly for senior+, especially in remote",
    source: "Compensation watcher",
    summary: "Comp bands show larger variance for senior engineers across the last 2 weeks.",
    category: "HIRING",
    readTime: "5 min",
  },
];

